export const FETCH_THUMBNAILS_REQUEST = 'FETCH_THUMBNAILS_REQUEST';
export const FETCH_THUMBNAILS_SUCCESS = 'FETCH_THUMBNAILS_SUCCESS';
export const FETCH_THUMBNAILS_FAILURE = 'FETCH_THUMBNAILS_FAILURE';